name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 192.168.1.100 >> ~/.ssh/known_hosts
      shell: bash

    - name: Deploy to Server
      run: |
        ssh hadi@192.168.1.100 "echo '✅ اتصال موفق از طرف GitHub!'"

